/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Compartment struct {
	Location *Location `json:"location,omitempty"`
	Name string `json:"name,omitempty"`
}
