/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CompartmentValidateResponse struct {
	SessionExpirationTime int32 `json:"sessionExpirationTime,omitempty"`
	SessionUuid string `json:"sessionUuid,omitempty"`
}
