/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ParcelCompartment struct {
	OpenCode string `json:"openCode,omitempty"`
	ShipmentNumber string `json:"shipmentNumber,omitempty"`
}
