/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type NotificationData struct {
	Content string `json:"content,omitempty"`
	Date time.Time `json:"date,omitempty"`
	F35560id string `json:"f35560id,omitempty"`
	ImageUrl string `json:"imageUrl,omitempty"`
	ParcelCount int32 `json:"parcelCount,omitempty"`
	Read bool `json:"read,omitempty"`
	Sender string `json:"sender,omitempty"`
	ShipmentNumber string `json:"shipmentNumber,omitempty"`
	Title string `json:"title,omitempty"`
	Type_ string `json:"type,omitempty"`
}
