/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgreementGrant struct {
	AgreementType string `json:"agreementType,omitempty"`
	Email string `json:"email,omitempty"`
	Status string `json:"status,omitempty"`
}
