/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CashOnDelivery struct {
	Paid bool `json:"paid,omitempty"`
	PayCode string `json:"payCode,omitempty"`
	Price string `json:"price,omitempty"`
	Url string `json:"url,omitempty"`
}
