/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CompartmentClaimResponse struct {
	ActionTime int32 `json:"actionTime,omitempty"`
	ConfirmActionTime int32 `json:"confirmActionTime,omitempty"`
	OpenCompartmentWaitingTime int32 `json:"openCompartmentWaitingTime,omitempty"`
}
