/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeliveryPointData struct {
	AddressDetails *AddressDetails `json:"addressDetails,omitempty"`
	Location *PointLocation `json:"location,omitempty"`
	Location247 bool `json:"location247,omitempty"`
	LocationDescription string `json:"locationDescription,omitempty"`
	Name string `json:"name,omitempty"`
	OpeningHours string `json:"openingHours,omitempty"`
	PaymentType map[string]string `json:"paymentType,omitempty"`
	Status string `json:"status,omitempty"`
	Type_ []string `json:"type,omitempty"`
	Virtual int32 `json:"virtual,omitempty"`
}
