/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Location struct {
	Column int32 `json:"column,omitempty"`
	Row int32 `json:"row,omitempty"`
	Side string `json:"side,omitempty"`
}
