/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateTicketDetailsNetwork struct {
	Accepted bool `json:"accepted,omitempty"`
	Rma string `json:"rma,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
