/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateOrganizationTicketRequest struct {
	Address string `json:"address,omitempty"`
	Description string `json:"description,omitempty"`
	OrderNumber string `json:"orderNumber,omitempty"`
	OrganizationUuid string `json:"organizationUuid,omitempty"`
	ParcelSize string `json:"parcelSize,omitempty"`
	ReasonUuid string `json:"reasonUuid,omitempty"`
	Sender *ReturnSenderNetwork `json:"sender,omitempty"`
}
