/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CompartmentStatusResponse struct {
	Compartment *Compartment `json:"compartment,omitempty"`
	Status string `json:"status,omitempty"`
}
