/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MultiCompartment struct {
	Collected bool `json:"collected,omitempty"`
	Presentation bool `json:"presentation,omitempty"`
	ShipmentNumbers []string `json:"shipmentNumbers,omitempty"`
	Uuid string `json:"uuid,omitempty"`
}
