/*
 * Inpost Mobile
 *
 * Extracted from retrofit
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddressDetails struct {
	BuildingNumber string `json:"buildingNumber,omitempty"`
	City string `json:"city,omitempty"`
	FlatNumber string `json:"flatNumber,omitempty"`
	PostCode string `json:"postCode,omitempty"`
	Province string `json:"province,omitempty"`
	Street string `json:"street,omitempty"`
}
